# Generated by Django 3.2.25 on 2024-11-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_kdaa_school_kadaa'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='imag',
            field=models.ImageField(blank=True, default='C:=-transfer - 14\\projetabbas\templates\x07pp1\\image\\logo1.jpg', upload_to='pictures/'),
        ),
    ]
