# Generated by Django 3.2.25 on 2024-11-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_school_imag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='imag',
            field=models.ImageField(upload_to='abbas'),
        ),
    ]
