# Generated by Django 3.2.25 on 2024-11-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_school_imag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ps123note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anne', models.CharField(max_length=50)),
                ('classe', models.CharField(max_length=50)),
                ('groupe', models.CharField(max_length=50)),
                ('champ', models.CharField(max_length=50)),
                ('souschamp', models.CharField(max_length=50)),
                ('rem1', models.CharField(max_length=50)),
                ('rem2', models.CharField(max_length=50)),
                ('rem3', models.CharField(max_length=50)),
                ('num1', models.IntegerField(verbose_name='10')),
                ('num2', models.IntegerField(verbose_name='10')),
            ],
        ),
    ]
