# Generated by Django 3.2.25 on 2024-11-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_ps123note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ps123note',
            name='champ',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ps123note',
            name='groupe',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ps123note',
            name='souschamp',
            field=models.CharField(max_length=100),
        ),
    ]
