# Generated by Django 3.2.25 on 2024-11-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20241128_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='regeleveps',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code1', models.CharField(max_length=50)),
                ('nom1', models.CharField(max_length=50)),
                ('pere1', models.CharField(max_length=50)),
                ('famille1', models.CharField(max_length=50)),
                ('anne1', models.CharField(max_length=50)),
                ('mois', models.CharField(max_length=50)),
                ('classe1', models.CharField(max_length=50)),
                ('section1', models.CharField(max_length=50)),
                ('groupe', models.CharField(max_length=100)),
                ('champ', models.CharField(max_length=100)),
                ('souschamp', models.CharField(max_length=300)),
                ('rem11', models.CharField(max_length=100)),
                ('rem21', models.CharField(max_length=50)),
                ('rem31', models.CharField(max_length=50)),
                ('num11', models.IntegerField(verbose_name='10')),
                ('num21', models.IntegerField(verbose_name='10')),
                ('sem1', models.CharField(max_length=50)),
                ('sem2', models.CharField(max_length=50)),
                ('sem3', models.CharField(max_length=50)),
                ('sem4', models.CharField(max_length=50)),
                ('sem5', models.CharField(max_length=50)),
                ('sem6', models.CharField(max_length=50)),
                ('sem7', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='ps123note',
            name='rem1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ps123note',
            name='souschamp',
            field=models.CharField(max_length=300),
        ),
    ]
