# Generated by Django 3.2.25 on 2024-12-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20241128_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='mony',
            name='td',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mony',
            name='tl',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
