# Generated by Django 3.2.25 on 2024-12-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_mediaschool'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaschool',
            name='rem3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mediaschool',
            name='rem1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mediaschool',
            name='rem2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
