# Generated by Django 3.2.25 on 2024-12-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20241213_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaschool',
            name='image',
            field=models.ImageField(null=True, upload_to='Users/Public/Pictures/Sample Pictures'),
        ),
    ]
