# Generated by Django 3.2.25 on 2024-12-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_mediaschool_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaschool',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mediaschool',
            name='video',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
