# Generated by Django 3.2.25 on 2024-12-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_auto_20241213_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaschool',
            name='image',
            field=models.ImageField(null=True, upload_to='static/image/'),
        ),
        migrations.AlterField(
            model_name='mediaschool',
            name='video',
            field=models.FileField(null=True, upload_to='static/image/'),
        ),
    ]
