# Generated by Django 3.2.25 on 2024-12-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_auto_20241213_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoschool',
            name='video',
            field=models.FileField(null=True, upload_to='static/image/'),
        ),
    ]
