# Generated by Django 3.2.25 on 2024-12-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_alter_videoschool_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsschool',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dat', models.DateField()),
                ('news1', models.CharField(max_length=50, null=True)),
                ('rem1', models.CharField(max_length=50, null=True)),
                ('rem2', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
