# Generated by Django 3.2.25 on 2024-12-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_newsschool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsschool',
            name='news1',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
