# Generated by Django 3.2.25 on 2024-12-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_alter_newsschool_news1'),
    ]

    operations = [
        migrations.AddField(
            model_name='anne',
            name='vexa1',
            field=models.CharField(default=95745, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anne',
            name='vexa2',
            field=models.CharField(default=534, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anne',
            name='vsem1',
            field=models.CharField(default=49058, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anne',
            name='vsem2',
            field=models.CharField(default=-405, max_length=50),
            preserve_default=False,
        ),
    ]
