# Generated by Django 3.2.25 on 2024-12-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_auto_20241228_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regeleve',
            name='pass1',
            field=models.DecimalField(decimal_places=0, max_digits=7),
        ),
    ]
