# Generated by Django 3.2.25 on 2025-01-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_alter_regeleve_pass1'),
    ]

    operations = [
        migrations.AddField(
            model_name='stok',
            name='passmod',
            field=models.CharField(default=11, max_length=50),
            preserve_default=False,
        ),
    ]
