# Generated by Django 3.2.25 on 2025-01-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_stok_passmod'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='exa1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matiere',
            name='exa2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matiere',
            name='sem1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matiere',
            name='sem2',
            field=models.IntegerField(default=0),
        ),
    ]
