# Generated by Django 3.2.25 on 2025-01-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_auto_20250103_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ps123note',
            name='num1',
            field=models.IntegerField(default=0, verbose_name='10'),
        ),
        migrations.AlterField(
            model_name='ps123note',
            name='num2',
            field=models.IntegerField(default=0, verbose_name='10'),
        ),
        migrations.AlterField(
            model_name='ps123note',
            name='rem1',
            field=models.CharField(default='x', max_length=100),
        ),
        migrations.AlterField(
            model_name='ps123note',
            name='rem2',
            field=models.CharField(default='x', max_length=50),
        ),
        migrations.AlterField(
            model_name='ps123note',
            name='rem3',
            field=models.CharField(default='x', max_length=50),
        ),
    ]
