# Generated by Django 3.2.25 on 2025-01-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_auto_20250105_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ps123note',
            name='num1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ps123note',
            name='num2',
            field=models.IntegerField(default=0),
        ),
    ]
