# Generated by Django 3.2.25 on 2025-02-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_auto_20250105_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='structurecarnet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anne', models.CharField(max_length=50)),
                ('mois', models.TextField()),
                ('code', models.IntegerField(verbose_name='10')),
                ('nombremy', models.IntegerField(verbose_name='10')),
                ('code1', models.IntegerField(verbose_name='10')),
                ('code2', models.IntegerField(verbose_name='10')),
                ('code3', models.IntegerField(verbose_name='10')),
                ('code4', models.IntegerField(verbose_name='10')),
                ('code5', models.IntegerField(verbose_name='10')),
                ('code6', models.IntegerField(verbose_name='10')),
                ('code7', models.IntegerField(verbose_name='10')),
                ('code8', models.IntegerField(verbose_name='10')),
                ('code9', models.IntegerField(verbose_name='10')),
                ('code10', models.IntegerField(verbose_name='10')),
                ('code11', models.IntegerField(verbose_name='10')),
                ('code12', models.IntegerField(verbose_name='10')),
                ('rem1', models.CharField(max_length=50, null=True)),
                ('rem2', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
