# Generated by Django 3.2.25 on 2025-02-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_alter_structurecarnet_mois'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structurecarnet',
            name='mois',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
