# Generated by Django 3.2.25 on 2025-02-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_alter_structurecarnet_mois'),
    ]

    operations = [
        migrations.AddField(
            model_name='regeleve',
            name='matiere1',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regeleve',
            name='matiere2',
            field=models.DecimalField(decimal_places=2, default=212, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regeleve',
            name='matiere3',
            field=models.DecimalField(decimal_places=2, default=121, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regeleve',
            name='matiere4',
            field=models.DecimalField(decimal_places=2, default=21, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regeleve',
            name='matiere5',
            field=models.DecimalField(decimal_places=2, default=21, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regeleve',
            name='matiere6',
            field=models.DecimalField(decimal_places=2, default=21, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regeleve',
            name='matiere7',
            field=models.DecimalField(decimal_places=2, default=21, max_digits=7),
            preserve_default=False,
        ),
    ]
