# Generated by Django 3.2.25 on 2025-02-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_auto_20250222_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='regeleve',
            name='anne',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regeleve',
            name='code',
            field=models.IntegerField(default=1, verbose_name='10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regeleve',
            name='code01',
            field=models.IntegerField(default=0, verbose_name='10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regeleve',
            name='code10',
            field=models.IntegerField(default=1, verbose_name='10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regeleve',
            name='code11',
            field=models.IntegerField(default=1, verbose_name='10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regeleve',
            name='code12',
            field=models.IntegerField(default=1, verbose_name='10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regeleve',
            name='code2',
            field=models.IntegerField(default=1, verbose_name='10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regeleve',
            name='code3',
            field=models.IntegerField(default=1, verbose_name='10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regeleve',
            name='code4',
            field=models.IntegerField(default=1, verbose_name='10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regeleve',
            name='code5',
            field=models.IntegerField(default=1, verbose_name='10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regeleve',
            name='code6',
            field=models.IntegerField(default=1, verbose_name='10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regeleve',
            name='code7',
            field=models.IntegerField(default=1, verbose_name='10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regeleve',
            name='code8',
            field=models.IntegerField(default=1, verbose_name='10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regeleve',
            name='code9',
            field=models.IntegerField(default=1, verbose_name='10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regeleve',
            name='nombremy',
            field=models.IntegerField(default=1, verbose_name='10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regeleve',
            name='rem1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='regeleve',
            name='rem2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
