# Generated by Django 3.2.25 on 2025-03-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_auto_20250224_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structurecarnet',
            name='code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='structurecarnet',
            name='code1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='structurecarnet',
            name='code10',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='structurecarnet',
            name='code11',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='structurecarnet',
            name='code12',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='structurecarnet',
            name='code2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='structurecarnet',
            name='code3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='structurecarnet',
            name='code4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='structurecarnet',
            name='code5',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='structurecarnet',
            name='code6',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='structurecarnet',
            name='code7',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='structurecarnet',
            name='code8',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='structurecarnet',
            name='code9',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='structurecarnet',
            name='nombremy',
            field=models.IntegerField(),
        ),
    ]
