# Generated by Django 3.2.25 on 2025-03-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_auto_20250303_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regeleve',
            name='code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='regeleve',
            name='code01',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='regeleve',
            name='code10',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='regeleve',
            name='code11',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='regeleve',
            name='code12',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='regeleve',
            name='code2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='regeleve',
            name='code3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='regeleve',
            name='code4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='regeleve',
            name='code5',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='regeleve',
            name='code6',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='regeleve',
            name='code7',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='regeleve',
            name='code8',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='regeleve',
            name='code9',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='regeleve',
            name='nombremy',
            field=models.IntegerField(),
        ),
    ]
