# Generated by Django 3.2.25 on 2025-03-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_auto_20250303_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='nomforcarnet',
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matiere',
            name='sousnom',
            field=models.CharField(default=122, max_length=50),
            preserve_default=False,
        ),
    ]
