# Generated by Django 3.2.25 on 2025-03-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_auto_20250306_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matiere',
            old_name='sousnom',
            new_name='sousnom1',
        ),
        migrations.AddField(
            model_name='matiere',
            name='sousnom2',
            field=models.CharField(default=211, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matiere',
            name='sousnom3',
            field=models.CharField(default=2121, max_length=50),
            preserve_default=False,
        ),
    ]
